import type { SessionSnapshot, Workspace } from "../types";
import { clock } from "../format";
export function InboxView({session, navigate, replay, busy, onReadHandover, handoverRead}: {session: SessionSnapshot; navigate: (view: Workspace) => void; replay: () => void; busy: boolean; onReadHandover: () => void; handoverRead: boolean}) {
  const profile = session.scenario_profile;
  return <div className="office-view"><div className="view-heading"><h1>Office / Inbox</h1><span>Shift handover · {clock(session.summary.simulated_minutes)}</span></div>
    <details className="handover-item" open={profile.id !== "tutorial-v1" || handoverRead} onToggle={e => {if (e.currentTarget.open) onReadHandover();}}><summary>Read first-shift handover · {profile.title}</summary><article className="briefing-letter"><div className="memo-meta"><span>From: Shift manager</span><span>To: Industrial engineering</span><span>00:00 · Handover</span></div><h2>{profile.title}</h2><p>{profile.briefing}</p><p>Starting condition: {profile.initial_conditions.raw_units} steel blanks, {Object.values(profile.initial_conditions.wip).reduce((a, b) => a + b, 0)} carried-in WIP units. Primary handover area: {profile.machines.find(m => m.id === profile.primary_zone)?.name ?? profile.primary_zone ?? "Component line"}.</p><button onClick={() => navigate("Plant View")}>Inspect the line</button></article></details>
    <section className="work-section decision-board"><div className="section-title"><div><h2>Decision board</h2><p>Three live prompts for this shift. They record the real plant state and your decisions; there is no preset “correct” move.</p></div><span>{profile.shift_review.actions_recorded} action{profile.shift_review.actions_recorded === 1 ? "" : "s"} logged</span></div><ol className="decision-list">{profile.decision_cards.map((card, index) => <li key={card.id}><span className="decision-number">{index + 1}</span><div><strong>{card.title}</strong><p>{card.detail}</p><small>{card.status} · {card.decision_logged ? "Player decision logged" : "No player decision logged"}</small></div><button onClick={() => navigate(card.workspace)}>Open {card.workspace}</button></li>)}</ol></section>
    <section className="work-section"><h2>Live shift notices</h2>{session.shift_events?.filter(e => e.state === "active").map(e => <p key={e.id}><strong>{e.severity} · {e.title}</strong> — {e.detail} <button onClick={() => navigate(e.workspace)}>Owner: {e.workspace}</button></p>)}{!session.shift_events?.some(e => e.state === "active") && <p>No active shift events. Upcoming events appear in the shift timeline.</p>}</section>
    <section className="work-section"><h2>Current engineering tasks</h2><p>Tasks follow live operational concerns. They clear as the underlying condition changes.</p><ul className="task-list">{profile.active_alerts.map(alert => <li key={alert.id}><span className={`signal ${alert.severity}`}/><div><strong>{alert.workspace}</strong><p>{alert.message}</p></div><button onClick={() => navigate(alert.workspace)}>Review</button></li>)}</ul>{!profile.active_alerts.length && <p>No active exceptions. Monitor delivery progress as the shift advances.</p>}</section>
    <section className="work-section"><button disabled={busy} onClick={replay}>Replay tutorial</button></section>
    <section className="work-section"><h2>Production-control note</h2><p>Priorities decide ties between orders with the same due time. Material is allocated automatically from finished goods. All costs and decisions remain attached to this shift.</p></section>
  </div>;
}
