import { useState } from "react";
import type { PlantSession } from "../hooks/usePlantSession";
import { clock, label, money, percent } from "../format";
export function InventoryView({control}: {control: PlantSession}) {
  const session = control.session!;
  const s = session.summary;
  const supply = s.supply_summary;
  const supplier = session.scenario_profile.suppliers[0];
  const [quantity, setQuantity] = useState("100");
  return <div className="office-view"><div className="view-heading"><h1>Inventory</h1><span>Raw material, WIP and finished goods</span></div>
    <dl className="readings horizontal"><div><dt>Raw on hand</dt><dd>{s.raw_material_remaining}</dd></div><div><dt>WIP in buffers</dt><dd>{s.wip}</dd></div><div><dt>FG available</dt><dd>{s.finished_goods_available}</dd></div><div><dt>FG allocated</dt><dd>{s.finished_goods_allocated}</dd></div><div><dt>Inbound units</dt><dd>{supply.inbound_units}</dd></div></dl>
    <section className="work-section"><h2>Place a purchase order</h2><p><strong>{supplier.id} · {supplier.name}</strong> — promised lead {supplier.min_lead_minutes}–{supplier.max_lead_minutes} minutes; late-delivery probability {percent(supplier.late_probability)}, up to {supplier.max_delay_minutes} extra minutes. Actual arrival is disclosed on receipt.</p><form className="purchase-form" onSubmit={event => {event.preventDefault(); void control.purchase(supplier.id, Number(quantity));}}><label className="field">Raw units to order<input aria-label="Purchase quantity" type="number" required min="1" max="1000" step="1" value={quantity} onChange={e => setQuantity(e.target.value)} disabled={!!control.busy}/></label><span>{money(supplier.unit_cost)} / unit · proposed commitment {money(Number(quantity) * supplier.unit_cost)}</span><button className="primary" disabled={!!control.busy || quantity === ""} type="submit">Place purchase order</button></form><p className="table-note">Purchasing commits cost immediately. Stock increases only at receipt. No automatic purchasing or supplier-quality model is active.</p></section>
    <section className="work-section"><h2>Purchase register</h2><p>{supply.purchase_orders_open} open · {supply.purchase_orders_received} received · {supply.purchase_orders_late} late · {money(supply.procurement_committed_cost)} committed</p><div className="table-scroll"><table><thead><tr><th>PO</th><th>Quantity</th><th>Placed</th><th>Promised</th><th>Received</th><th>Status</th><th>Cost</th></tr></thead><tbody>{supply.purchase_orders.map(po => <tr key={po.id}><td>{po.id}</td><td>{po.quantity}</td><td>{clock(po.placed_minute)}</td><td>{clock(po.promised_receipt_minute)}</td><td>{po.actual_receipt_minute === null ? "Awaiting receipt" : clock(po.actual_receipt_minute)}</td><td>{label(po.status)}</td><td>{money(po.total_committed_cost)}</td></tr>)}{!supply.purchase_orders.length && <tr><td colSpan={7}>No purchase orders placed this shift. Review material coverage before the line runs short.</td></tr>}</tbody></table></div></section>
    <section className="work-section"><h2>Storage register</h2><div className="table-scroll"><table><thead><tr><th>Location</th><th>Units</th><th>Capacity</th><th>Condition</th></tr></thead><tbody>{session.scenario_profile.scene.zones.map(zone => <tr key={zone.id}><td>{label(zone.id)}</td><td>{zone.units}</td><td>{zone.capacity ?? "Uncapped storage"}</td><td>{zone.congested ? "Congested" : zone.units === 0 ? "Empty" : "Available"}</td></tr>)}</tbody></table></div><p className="table-note">Finished-goods total {s.finished_goods_total} = {s.finished_goods_available} available + {s.finished_goods_allocated} allocated = {s.good_production} good production.</p></section>
  </div>;
}
