import { useState } from "react";
import { useI18n } from "../i18n";
import type { PlantSession } from "../hooks/usePlantSession";
import { clock } from "../format";
export function InventoryView({control}: {control: PlantSession}) {
  const { t, label, money, percent } = useI18n();
  const session = control.session!;
  const s = session.summary;
  const supply = s.supply_summary;
  const supplier = session.scenario_profile.suppliers[0];
  const [quantity, setQuantity] = useState("100");
  return <div className="office-view"><div className="view-heading"><h1>{t("Inventory")}</h1><span>{t("Raw material, WIP and finished goods")}</span></div>
    <dl className="readings horizontal"><div><dt>{t("Raw on hand")}</dt><dd>{s.raw_material_remaining}</dd></div><div><dt>{t("WIP in buffers")}</dt><dd>{s.wip}</dd></div><div><dt>{t("FG available")}</dt><dd>{s.finished_goods_available}</dd></div><div><dt>{t("FG allocated")}</dt><dd>{s.finished_goods_allocated}</dd></div><div><dt>{t("Inbound units")}</dt><dd>{supply.inbound_units}</dd></div></dl>
    <section className="work-section"><h2>{t("Place a purchase order")}</h2><p><strong>{supplier.id} · {supplier.name}</strong>{" " + t("— promised lead {value1}–{value2} minutes; late-delivery probability {value3}, up to {value4} extra minutes. Expected receipt includes modeled transit disruptions; actual arrival is recorded on receipt.", {value1: supplier.min_lead_minutes, value2: supplier.max_lead_minutes, value3: percent(supplier.late_probability), value4: supplier.max_delay_minutes})}</p><form className="purchase-form" onSubmit={event => {event.preventDefault(); void control.purchase(supplier.id, Number(quantity));}}><label className="field">{t("Raw units to order")}<input aria-label={t("Purchase quantity")} type="number" required min="1" max="1000" step="1" value={quantity} onChange={e => setQuantity(e.target.value)} disabled={!!control.busy}/></label><span>{t("{value1} / unit · proposed commitment {value2}", {value1: money(supplier.unit_cost), value2: money(Number(quantity) * supplier.unit_cost)})}</span><button className="primary" disabled={!!control.busy || quantity === "" || s.simulated_minutes >= s.shift_minutes} type="submit">{t("Place purchase order")}</button></form><p className="table-note">{t("Purchasing commits cost immediately. Stock increases only at receipt. No automatic purchasing or supplier-quality model is active.")}</p></section>
    <section className="work-section"><h2>{t("Purchase register")}</h2><p>{t("{value1} open · {value2} received · {value3} late · {value4} committed", {value1: supply.purchase_orders_open, value2: supply.purchase_orders_received, value3: supply.purchase_orders_late, value4: money(supply.procurement_committed_cost)})}</p><div className="table-scroll"><table><thead><tr><th>PO</th><th>{t("Quantity")}</th><th>{t("Placed")}</th><th>{t("Promised")}</th><th>{t("Expected / actual")}</th><th>{t("Status")}</th><th>{t("Cost")}</th><th>{t("Expedite")}</th></tr></thead><tbody>{supply.purchase_orders.map(po => <tr key={po.id}><td>{po.id}</td><td>{po.quantity}</td><td>{clock(po.placed_minute)}</td><td>{clock(po.promised_receipt_minute)}</td><td>{t("{value1} expected", {value1: clock(po.expected_receipt_minute ?? po.promised_receipt_minute)})}<br/>{po.actual_receipt_minute === null ? t("Awaiting receipt") : clock(po.actual_receipt_minute)}</td><td>{label(po.status)}{po.supplier_late && <small>{t("Later than original promise")}</small>}</td><td>{money(po.total_committed_cost)}<small>{t("Expedite {value1}", {value1: money(po.expedite_cost ?? 0)})}</small></td><td><button disabled={!!control.busy || po.status !== "OPEN" || po.expedited || s.simulated_minutes >= s.shift_minutes} onClick={() => void control.expeditePurchase(po.id)}>{t("Expedite · 120")}</button><small>{po.expedited ? t("Expedited once") : po.status !== "OPEN" ? t("Already received") : s.simulated_minutes >= s.shift_minutes ? t("Shift closed") : t("Halve remaining transit time")}</small></td></tr>)}{!supply.purchase_orders.length && <tr><td colSpan={8}>{t("No purchase orders placed this shift. Review material coverage before the line runs short.")}</td></tr>}</tbody></table></div></section>
    <section className="work-section"><h2>{t("Storage register")}</h2><p>{t("{value1} units of demand lack material coverage before scrap allowance. Coverage includes raw, inbound, queued WIP, in-process units and unallocated finished goods.", {value1: session.scenario_profile.scene.receiving.uncovered_demand})}</p><div className="table-scroll"><table><thead><tr><th>{t("Location")}</th><th>{t("Units")}</th><th>{t("Capacity")}</th><th>{t("Condition")}</th></tr></thead><tbody>{session.scenario_profile.scene.zones.map(zone => <tr key={zone.id}><td>{label(zone.id)}</td><td>{zone.units}</td><td>{zone.capacity ?? t("Uncapped storage")}</td><td>{zone.congested ? t("Congested") : zone.units === 0 ? t("Empty") : t("Available")}</td></tr>)}</tbody></table></div><p className="table-note">{t("Finished-goods total {value1} = {value2} available + {value3} allocated = {value4} good production.", {value1: s.finished_goods_total, value2: s.finished_goods_available, value3: s.finished_goods_allocated, value4: s.good_production})}</p></section>
  </div>;
}
