import type { PlantSession } from "../hooks/usePlantSession";
import { MachineActions } from "../components/MachineActions";
import { percent } from "../format";
export function QualityView({control}: {control: PlantSession}) {
  const session = control.session!;
  const containment = session.quality_containment;
  const s = session.summary;
  const quality = s.machine_metrics.quality_01;
  const stage = session.scenario_profile.machines.find(m => m.id === "quality_01")!;
  return <div className="office-view"><div className="view-heading"><h1>Quality</h1><span>Final inspection and containment</span></div>
    <dl className="readings horizontal"><div><dt>Inspected units</dt><dd>{quality.processed}</dd></div><div><dt>Released by inspection</dt><dd>{s.good_production}</dd></div><div><dt>Scrapped</dt><dd>{s.scrap}</dd></div><div><dt>Observed yield</dt><dd>{quality.processed ? percent(s.quality) : "No inspections yet"}</dd></div><div><dt>Configured lot reject risk</dt><dd>{percent(stage.scrap_probability)}</dd></div></dl>
    {s.equipment_quality && <section className="work-section"><h2>Equipment quality trail</h2><dl className="readings horizontal"><div><dt>Cutting source rejects</dt><dd>{s.equipment_quality.source_rejects}</dd></div><div><dt>Downstream residue catches</dt><dd>{s.equipment_quality.downstream_catches}</dd></div><div><dt>Rework / retests</dt><dd>{s.equipment_quality.rework}</dd></div><div><dt>Latent WIP</dt><dd>{s.equipment_quality.latent_wip}</dd></div><div><dt>All-stage scrap</dt><dd>{s.total_scrap}</dd></div></dl><p>Wash residue follows individual parts. Tester drift reduces detection; inspection overload slows release and weakens sampling. Containment catches residue in newly inspected parts. Servicing the wash prevents future exposure but does not clean existing WIP.</p></section>}
    {session.scenario_profile.machines.filter(m => ["wash_01", "test_01", "quality_01"].includes(m.id)).map(asset => {const metric = s.machine_metrics[asset.id]; return <section className="maintenance-row" key={asset.id}><div><h2>{asset.id.replace("_", "-").toUpperCase()}</h2><p>{metric.condition_label}: {metric.condition_value?.toFixed(1)} / 100 · {metric.cycle_time_multiplier?.toFixed(2)}× cycle</p><p>{metric.active_issue ?? "Within control limits"}</p></div>{metric.service && <MachineActions asset={asset} metric={metric} control={control}/>}</section>;})}
    {containment && <section className="work-section"><h2>Containment plan · {containment.active ? "Active" : "Not active"}</h2><p>Each new final inspection adds 0.6 minutes and 2 cost. Latent defects found are isolated as scrap. Previously released defects cannot be recalled by this action.</p><button disabled={!!control.busy || !!containment.unavailable_reason} onClick={() => void control.contain()}>Activate intensified inspection</button><p>{containment.unavailable_reason ?? "Available for detected quality exposure"}</p><dl className="readings horizontal"><div><dt>Intensified inspections started</dt><dd>{containment.inspected_units}</dd></div><div><dt>Added workload</dt><dd>{containment.added_inspection_minutes.toFixed(1)} min</dd></div><div><dt>Inspection cost</dt><dd>{containment.inspection_cost}</dd></div><div><dt>Latent defects isolated</dt><dd>{containment.captured_units}</dd></div><div><dt>Customer escapes</dt><dd>{containment.customer_escapes}</dd></div><div><dt>Suspect FG not allocated</dt><dd>{containment.suspect_finished_units}</dd></div></dl></section>}
    <section className="work-section"><h2>Observed rejection breakdown</h2>{session.scenario_profile.machines.filter(m => s.machine_metrics[m.id].scrap > 0).sort((a,b) => s.machine_metrics[b.id].scrap - s.machine_metrics[a.id].scrap).map(m => <div className="defect-row" key={m.id}><span>{m.name}: {s.machine_metrics[m.id].scrap} rejected</span><meter aria-label={`${m.name} rejected units`} min={0} max={Math.max(1, s.total_scrap ?? s.scrap)} value={s.machine_metrics[m.id].scrap}/></div>)}{(s.total_scrap ?? s.scrap) === 0 && <p>No observed rejections yet.</p>}<p className="table-note">Cutting rejects and downstream residue catches retain asset attribution. Latent containment scrap is included in total scrap.</p></section>
    <section className="work-section"><h2>Inspection disposition</h2><div className="table-scroll"><table><thead><tr><th>Disposition</th><th>Actual units</th><th>Consequence</th></tr></thead><tbody><tr><td>Accepted</td><td>{s.good_production}</td><td>Received into finished goods and made available for customer allocation.</td></tr><tr><td>Non-conforming / scrapped</td><td>{s.scrap}</td><td>Removed from production; cannot satisfy customer orders.</td></tr></tbody></table></div><p>Every completed Quality cycle makes a seeded inspection decision. The event log records rejected units. The lot risk is a scenario parameter; observed yield is calculated from actual inspection outcomes. Released output may include latent defects. Customer escapes count only suspect units allocated to orders, separately from scrap.</p></section>
    <section className="work-section"><h2>Quality concerns</h2>{session.scenario_profile.active_alerts.filter(a => a.workspace === "Quality").map(a => <p key={a.id}>{a.message}</p>)}<p>Normal inspection scrap is separate from latent defects. On quality-containment profiles, 6% of units passing normal inspection carry a modeled latent defect (12% during a quality notice). Containment detects and scraps those defects; without it, suspect units can reach customers. Source risk is unchanged.</p></section>
  </div>;
}
