import { useI18n } from "../i18n";
import type { PlantSession } from "../hooks/usePlantSession";
import { MachineActions } from "../components/MachineActions";

export function QualityView({control}: {control: PlantSession}) {
  const { t, percent } = useI18n();
  const session = control.session!;
  const containment = session.quality_containment;
  const s = session.summary;
  const quality = s.machine_metrics.quality_01;
  const stage = session.scenario_profile.machines.find(m => m.id === "quality_01")!;
  return <div className="office-view"><div className="view-heading"><h1>{t("Quality")}</h1><span>{t("Final inspection and containment")}</span></div>
    <dl className="readings horizontal"><div><dt>{t("Inspected units")}</dt><dd>{quality.processed}</dd></div><div><dt>{t("Released by inspection")}</dt><dd>{s.good_production}</dd></div><div><dt>{t("Scrapped")}</dt><dd>{s.scrap}</dd></div><div><dt>{t("Observed yield")}</dt><dd>{quality.processed ? percent(s.quality) : t("No inspections yet")}</dd></div><div><dt>{t("Configured lot reject risk")}</dt><dd>{percent(stage.scrap_probability)}</dd></div></dl>
    {s.equipment_quality && <section className="work-section"><h2>{t("Equipment quality trail")}</h2><dl className="readings horizontal"><div><dt>{t("Cutting source rejects")}</dt><dd>{s.equipment_quality.source_rejects}</dd></div><div><dt>{t("Downstream residue catches")}</dt><dd>{s.equipment_quality.downstream_catches}</dd></div><div><dt>{t("Rework / retests")}</dt><dd>{s.equipment_quality.rework}</dd></div><div><dt>{t("Latent WIP")}</dt><dd>{s.equipment_quality.latent_wip}</dd></div><div><dt>{t("All-stage scrap")}</dt><dd>{s.total_scrap}</dd></div></dl><p>{t("Wash residue follows individual parts. Tester drift reduces detection; inspection overload slows release and weakens sampling. Containment catches residue in newly inspected parts. Servicing the wash prevents future exposure but does not clean existing WIP.")}</p></section>}
    {session.scenario_profile.machines.filter(m => ["wash_01", "test_01", "quality_01"].includes(m.id)).map(asset => {const metric = s.machine_metrics[asset.id]; return <section className="maintenance-row" key={asset.id}><div><h2>{asset.id.replace("_", "-").toUpperCase()}</h2><p>{t("{value1}: {value2} / 100 · {value3}× cycle", {value1: metric.condition_label, value2: metric.condition_value?.toFixed(1), value3: metric.cycle_time_multiplier?.toFixed(2)})}</p><p>{metric.active_issue ?? t("Within control limits")}</p></div>{metric.service && <MachineActions asset={asset} metric={metric} control={control}/>}</section>;})}
    {containment && <section className="work-section"><h2>{t("Containment plan · {value1}", {value1: containment.active ? t("Active") : t("Not active")})}</h2><p>{t("Each new final inspection adds 0.6 minutes and 2 cost. Latent defects found are isolated as scrap. Previously released defects cannot be recalled by this action.")}</p><button disabled={!!control.busy || !!containment.unavailable_reason} onClick={() => void control.contain()}>{t("Activate intensified inspection")}</button><p>{containment.unavailable_reason ?? t("Available for detected quality exposure")}</p><dl className="readings horizontal"><div><dt>{t("Intensified inspections started")}</dt><dd>{containment.inspected_units}</dd></div><div><dt>{t("Added workload")}</dt><dd>{t("{value1} min", {value1: containment.added_inspection_minutes.toFixed(1)})}</dd></div><div><dt>{t("Inspection cost")}</dt><dd>{containment.inspection_cost}</dd></div><div><dt>{t("Latent defects isolated")}</dt><dd>{containment.captured_units}</dd></div><div><dt>{t("Customer escapes")}</dt><dd>{containment.customer_escapes}</dd></div><div><dt>{t("Suspect FG not allocated")}</dt><dd>{containment.suspect_finished_units}</dd></div></dl></section>}
    <section className="work-section"><h2>{t("Observed rejection breakdown")}</h2>{session.scenario_profile.machines.filter(m => s.machine_metrics[m.id].scrap > 0).sort((a,b) => s.machine_metrics[b.id].scrap - s.machine_metrics[a.id].scrap).map(m => <div className="defect-row" key={m.id}><span>{t("{value1}: {value2} rejected", {value1: m.name, value2: s.machine_metrics[m.id].scrap})}</span><meter aria-label={t("{value1} rejected units", {value1: m.name})} min={0} max={Math.max(1, s.total_scrap ?? s.scrap)} value={s.machine_metrics[m.id].scrap}/></div>)}{(s.total_scrap ?? s.scrap) === 0 && <p>{t("No observed rejections yet.")}</p>}<p className="table-note">{t("Cutting rejects and downstream residue catches retain asset attribution. Latent containment scrap is included in total scrap.")}</p></section>
    <section className="work-section"><h2>{t("Inspection disposition")}</h2><div className="table-scroll"><table><thead><tr><th>{t("Disposition")}</th><th>{t("Actual units")}</th><th>{t("Consequence")}</th></tr></thead><tbody><tr><td>{t("Accepted")}</td><td>{s.good_production}</td><td>{t("Received into finished goods and made available for customer allocation.")}</td></tr><tr><td>{t("Non-conforming / scrapped")}</td><td>{s.scrap}</td><td>{t("Removed from production; cannot satisfy customer orders.")}</td></tr></tbody></table></div><p>{t("Every completed Quality cycle makes a seeded inspection decision. The event log records rejected units. The lot risk is a scenario parameter; observed yield is calculated from actual inspection outcomes. Released output may include latent defects. Customer escapes count only suspect units allocated to orders, separately from scrap.")}</p></section>
    <section className="work-section"><h2>{t("Quality concerns")}</h2>{session.scenario_profile.active_alerts.filter(a => a.workspace === "Quality").map(a => <p key={a.id}>{a.message}</p>)}<p>{t("Normal inspection scrap is separate from latent defects. On quality-containment profiles, 6% of units passing normal inspection carry a modeled latent defect (12% during a quality notice). Containment detects and scraps those defects; without it, suspect units can reach customers. Source risk is unchanged.")}</p></section>
  </div>;
}
